name: logging-system

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout/@v3

      - name: copy secret to application.properties
      - run: echo ${{ secrets.APPLICATION_DEV_PROPERTIES }} > ./src/main/resources/application-dev.properties
      - run: cat ./src/main/resources/application-dev.properties

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: liberica

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew build
        shell: bash
